name: Build Latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      
    - name: Run versioning script
      run: .\version.bat
      
    - name: Build Policy Plus
      run: msbuild PolicyPlus.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PolicyPlus-Hebrew
        path: PolicyPlus\bin\Release\Policy Plus.exe

    # השלב הזה כנראה ימשיך להיכשל אצלך וזה בסדר גמור
    - name: Upload to S3
      continue-on-error: true
      uses: stcalica/s3-upload@0.0.1
      with:
        args: PolicyPlus\bin\Release\Policy Plus.exe
      env:
        FILE: PolicyPlus\bin\Release\Policy Plus.exe
        AWS_REGION: 'us-west-2'
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
